/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIew;

import java.util.Set;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Controller.dataHotel;
import Controller.dataQuartos;
/**
 *
 * @author edufr
 */
public class Adicionar extends javax.swing.JFrame {

    boolean v3 = false;
    boolean v2 = false;
    boolean v1 = false;
    String info2 ="";
    String info3 ="";
    String info4 ="";
    String a = "";
    String b = "";
    String c = "";
    String d = "";
    int pam = 0 ;
    String info = "";
    except e = new except();
    dataHotel dh = new dataHotel();
    dataQuartos dq = new dataQuartos();
  
 public Adicionar(String info1, String info2, boolean v1, String info3, boolean v2, String info4, boolean v3) {
        initComponents();
        inicializarValoresPadrao(info1, info2, v1, info3, v2, info4, v3);
    }

    // Adicione este construtor para usar valores padrão
    public Adicionar() {
        initComponents();
        inicializarValoresPadrao("", "", false, "", false, "", false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField3");

        jButton1.setText("Acionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              
        a = jTextField1.getText();
        b = jTextField2.getText();
        c = jTextField3.getText();
        d = jTextField4.getText();
        inf();
 
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void inicializarValoresPadrao(String info1, String info2, boolean v1, String info3, boolean v2, String info4, boolean v3) {
        jLabel1.setText(info1);
        jTextField2.setText("");
        jTextField1.setText("");
        jLabel2.setText(info2);
        jTextField2.setText("");
        jTextField2.setVisible(v1);

        jLabel3.setText(info3);
        jTextField3.setText("");
        jTextField3.setVisible(v2);

        jLabel4.setText(info4);
        jTextField4.setText("");
        jTextField4.setVisible(v3);
    }
    public void l1(String infoAdicional, String infoB) {
        jLabel1.setText(jLabel1.getText() + " " + infoAdicional);
        String a = jTextField1.getText();
        jButton1.setText(infoB);
    }
    
    public void l2(String infoAdicioonal1, String InfoAdicional2, String infoB)
    {
        jLabel1.setText(jLabel1.getText() + " " + infoAdicioonal1);
        jLabel2.setText(jLabel1.getText() + " " + InfoAdicional2);
        String a = jTextField1.getText();
        String b = jTextField2.getText();
        jTextField2.setVisible(true);
        jButton1.setText(infoB);
        
    }
    public void l3(String infoAdicioonal1, String InfoAdicional2, String InfoAdicional3, String infoBut)
    {
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jLabel1.setText(infoAdicioonal1);
        jLabel2.setText(InfoAdicional2);
        jLabel3.setText(InfoAdicional3);
        jButton1.setText(infoBut);
        
        
        
    }
    public void inf()
    {
       if(a != null)
       {
            info =  a + ";" ; 
       }   
       if(a != null && b!= null)
       {
            info = a + ";" + b + "; "; 
       }
        if (a != null && b!= null && c != null)
       {
            info = a + ";" + b + ";" + c + ";" ; 
       }
       if ( a != null && b!= null && c != null && c != null)
       {
            info =  a + ";" + b + "; " + c + ";" + d + ";"; 
       }
           
       Registro r  = new Registro();
       System.out.println(info);
       
       r.setCount(1);
       r.setVisible(true);
       
        if(jButton1.getText() =="Adicionar Hotel")
       {
           dh.setA(info);
           dh.setHotel();
       }
       else if(jButton1.getText() =="Atualizar Hotel")
       {
           dh.setA(info);
           dh.upHotel();
       }
       else if(jButton1.getText() == "Deletar Hotel")
       {
           dh.setA(info);
           dh.delHotel();   
       }
       else if(jButton1.getText() == "Adicionar Quarto")
       {
           dq.setA(info);
           dq.addQuartos();
       }
        else if(jButton1.getText() == "Atualizar Quarto")
       {    
            dq.setA(info);
            dq.upQuartos();
           
       }
        else if(jButton1.getText() == "Deletar Quarto")
       {
            dq.setA(info);
            dq.delQuartos();
       }
       dispose();

        
       
        
    }
    public int  getA(){
        return pam;
    }
    public String l4(String infoAdicioonal1, String InfoAdicional2, String InfoAdicional3, String InfoAdicional4)
    {
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jLabel1.setText(infoAdicioonal1);
        jLabel2.setText(InfoAdicional2);
        jLabel3.setText(InfoAdicional3);
        jLabel4.setText(InfoAdicional4);
        String a = jTextField1.getText();
        String b = jTextField2.getText();
        String c = jTextField3.getText();
        String d = jTextField4.getText();
        return a + b + c + d;
    }
     
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables


}
